### PR TITLE
OMEinsum as an alternative backend

### PR DESCRIPTION
**Pull request by GiggleLiu**
Nice package! I tried the contraction order optimizer in OMEinsum, the inference turns out to be much faster than the built in algorithm in instance 14 (should be one of the hardest).

```julia
julia> @time marginals = map(1:nvars) do openvertex
           code = popindices(tn.code, [openvertex])
           code(tensors...) |> LinearAlgebra.normalize!
       end;
  4.862772 seconds (13.84 M allocations: 5.292 GiB, 8.32% gc time, 1.60% compilation time)

julia> @time marginals = run_algo(obsvars, obsvals) |> x -> map(y -> y.vals, x);
102.955955 seconds (68.52 M allocations: 11.100 GiB, 1.59% gc time, 41.98% compilation time)
```

Check the source code and test for details. The algorithm implementation contains only ~30 lines of code, I am happy to discuss the details of the implementation. I am also curious about why the errors in the `reference_marginals` is so large? I breaks a lot of my tests. In your test case, you set a very high atol, which I think does not make sense though...

### CODE REVIEW

**Comment by mroavi** [comment]
Hi @GiggleLiu. Thanks a lot for this!

> I am also curious about why the errors in the reference_marginals is so large?

Ahh, this is a legacy thing. Initially, I was verifying the correctness of the marginals with [merlin](https://github.com/radum2275/merlin). This was the first hack I found to get around the floating-point number differences. But I will try to fix this.

Really cool how you managed to optimize the inference time with OMEinsum. I took a quick look at your code and realized that I will have to investigate a bit to understand everything you did there since I'm not that familiar with Einstein notation. Good to know that you are open to discuss. I will come back to you as soon as I have questions.

**Comment by mroavi** [comment]
Hi @GiggleLiu. I parametrized the algorithm such that the factor element type can be passed as an argument to the `run_algo` function. This fixes the issue above where I had to set a high `atol` to pass all of the tests. This test passes now:

```
    algo = compile_algo(
             uai_filepath,
             uai_evid_filepath = uai_evid_filepath,
             factor_eltype = Float32,
           )
    eval(algo)
    marginals = run_algo(obsvars, obsvals) |> x -> map(y -> y.vals, x)

    @test isapprox(marginals, reference_marginals)
```

I took some time to study your code. There are a few things that I don't fully understand. I really like your idea of using OMEinsum and OMEinsumContractionOrders.jl to contract the factors more efficiently. At the moment, I have no logic implemented to decide the order in which the sums and the products could be performed most efficiently.  Let me know if you have some time to discuss this.

**Comment by GiggleLiu** [comment]
Sounds great. Are you in Julia slack? Let us schedule a zoom meeting there

**Comment by GiggleLiu** [comment]
Just a quick update, after using the back-propagation approach, the time now is further reduced by more than two orders!

```julia
julia> @btime marginals2 = JunctionTrees.gradient(tn.code, generate_tensors(tn))[1:length(cards)] .|> LinearAlgebra.normalize!;
  24.365 ms (151828 allocations: 17.83 MiB)
```

In this code, I added some labels 1, 2, 3... (meaning vectors) into the code and feed vectors [1, 1] for each label.
Then I back propagate through the contraction process, and the gradients on the added labels are marginals.
Since Julia does not have a good automatic differentiation engine, I coded a naive AD engine for einsum inside.

However, I haven't figured out why my result is different from the reference marginal by a small number.

**Comment by mroavi** [comment]
That is pretty impressive! I benchmarked the same problem but this time I used Tamaki's algorithm to construct the tree decomposition.

```julia
algo = compile_algo(
         uai_filepath,
         uai_evid_filepath = uai_evid_filepath,
         apply_partial_evaluation = true,
         factor_eltype = Float32,
       )
eval(algo)
marginals = @btime run_algo($obsvars, $obsvals) |> x -> map(y -> y.vals, x)

# Filter the observed variables from the reference solution
reference_marginals_filtered = reference_marginals[setdiff(begin:end, obsvars)]

@test isapprox(marginals, reference_marginals_filtered)
```
```julia
  138.169 ms (30572 allocations: 16.51 MiB)
Test Passed
  Expression: isapprox(marginals, reference_marginals_filtered)
   Evaluated: isapprox(Vector{Float32}[[0.9962926, 0.0037074224], [0.99985343, 0.00014656382], [0.9991224, 0.0008776281], [0.9606877, 0.039312277], [0.9981463, 0.0018537112], [0.9258516, 0.074148454], [0.9995057, 0.00049427047], [0.99998474, 1.52375505f-5], [0.9962926, 0.003707422], [0.99998474, 1.5237552f-5]  …  [0.9024855, 0.097514525], [0.9333989, 0.06660107], [0.93709874, 0.06290124], [0.974134, 0.025865918], [0.97581434, 0.024185656], [0.9823956, 0.017604385], [0.9861012, 0.013898813], [0.9898071, 0.010192874], [0.9935134, 0.0064865644], [0.9953667, 0.0046333154]], [[0.996293, 0.00370742], [0.999853, 0.000146564], [0.999122, 0.000877628], [0.960688, 0.0393123], [0.998146, 0.00185371], [0.925852, 0.0741484], [0.999506, 0.000494271], [0.999985, 1.52376e-5], [0.996293, 0.00370742], [0.999985, 1.52376e-5]  …  [0.902485, 0.0975145], [0.933399, 0.0666011], [0.937099, 0.0629012], [0.974134, 0.0258659], [0.975814, 0.0241857], [0.982396, 0.0176044], [0.986101, 0.0138988], [0.989807, 0.0101929], [0.993513, 0.00648656], [0.995367, 0.00463331]])
```
Your approach is still faster: 24.365 ms vs 138.169 ms.

**Comment by GiggleLiu** [comment]
> But it is important to have in mind that you are benchmarking the whole process (including the construction of the tree decomposition, aka the junction tree) while, in my case, I'm only benchmarking the tensor contraction (aka message passing) stage of the algo.

I also only benchmarked the contraction. Tamaki’s algorithm is impressive too, I wish I can be one of the contraction order optimizer in OMEinsumContractionOrders in the future.

**Comment by mroavi** [comment]
> I also only benchmarked the contraction

Ahh ok.

> About the result correctness. Where is the reference marginal from

The reference marginals were provided by the UAI 2014 inference competition together with the models. You can find them here: https://personal.utdallas.edu/~vibhav.gogate/uai14-competition/files/ (MAR_prob.tar.gz contains the model definitions, MAR_sol.tar.gz contains the reference marginals). The formats of these files are explained here: https://personal.utdallas.edu/~vxg112130/uai14-competition/modelformat.html.

> Maybe we should try smaller examples so that we can compare with brute force.

Good idea. I will prepare some and share them with you.

**Comment by GiggleLiu** [comment]
@mroavi I added more comments. Feel free to comment in this PR if you have any question about the code.

**Comment by mroavi** [comment]
Closing in favor of https://github.com/mroavi/JunctionTrees.jl/pull/8 and https://github.com/mroavi/TensorInference.jl

**Pull request closed without merging**
